variables:
  IMAGE_NAME: registry.digitwalk.com/uikit

stages:
  - build
  - push
  - deploy
  - cleanup

build_staging:
  stage: build
  script:
    - npm run build
    - docker build -t $IMAGE_NAME .
  only:
    - develop
  tags:
    - build

push_staging:
  stage: push
  script:
    - docker push $IMAGE_NAME
  only:
    - develop
  tags:
    - push

deploy_staging:
  stage: deploy
  script:
    - docker-compose -f staging.yml pull
    - docker-compose -f staging.yml up -d
  only:
    - develop
  tags:
    - staging

cleanup_staging:
  stage: cleanup
  script:
    - EMPTYIMAGE=$(docker images | awk '{print $1, $3}' | grep '^<none>' | awk '{print $2}') sh -c 'if [ ! -z "$EMPTYIMAGE" ]; then docker rmi $EMPTYIMAGE; fi'
  only:
    - develop
  tags:
    - staging
  allow_failure: true
